### ISSUE TITLE
Unclear on how to deploy and start the service

### ISSUE THREAD

**Issue by mbariola** [satrd/poi_fusion_engine3#2]
Hi, I could not find a way to get directly in touch with the maintainers. 

I am a neophyte at Tomcat/Java and find unclear the installation part of the Service component. I have a fully functional Vagrant installation with all the needed components, but am unsure about how to configure and activate the service part.

Could you better detail step by step what to do with the "service" part and how to make sure it "talks" properly to the postgresql installation? I am not sure where to put it and how to invoke it.

I was able to install the frontend via Tomcat's Manager, but Frontend does not seem to properly write configuration but does not give any error out either, see attached image. I suspect it's all connected to the proper configuration and run of the Service part.

Any clarification with steps would be greatly appreciated.

Kind regards
![screenshot 2015-09-12 17 50 51](https://cloud.githubusercontent.com/assets/4893151/9832332/8ac92344-5977-11e5-854b-4c4a3902eefb.png)

**Comment by benmomo** [comment]
Hi,
I'm not familiar with Vagrant environment, thus I cannot guide if the problem has something to do with this configuration. Have you tried to install the service without Vagrant?
Anyway, from the snapshot in your e-mail, it seems that the initialization process ended in a state without feedback information, thus you don't see any message. Some hints:
- Did you install PostgreSQL with POSTGIS support? Have you checked it?
- There are some  SQL files that are stored in POSTGIS? Have you tried that there are no problem via pgAdmin3 or a similar software?
- What version of Apache Tomcat and Linux are you using? Depending on the version, you should change the Tomcat installation directory in the SQL files. This is explained in the documentation files. This can be a potential reason.
- Even if there is no message in the UI (snapshot), there are other ways to find the error. You should have a look at the Tomcat log file (<tomcat_dir>/ logs/catalina.out) and the log file of the application (located in the same directory). Probably you should find here an ERROR informing about the error.

Please try to follow these instructions and let me know if it helps. If you are unsure, please send me the log files.

Kind regards,
Benjamin

**Comment by mbariola** [comment]
Hi Benjamin, thanks for getting in touch, will answer each point. Sorry if it took a while because I wanted to make extra sure I had done everything as per the instructions and doing some extra investigation.

My Vagrant box is an Ubuntu server 14.10, with all the packages required by the Fusion Engine and some more for other technologies (I have checked and they do not conflict). 
(Actually, if you had some time to look into Vagrant, it would be a very helpful thing if you packaged a virtual machine with Fusion Engine, everybody could get it up and running as a baseline server with no room for error.)

This is the sequence of commands I launch to bring the plain server to one with all what I need:

```
sudo apt-get update
```

# all the packages requested in the Fusion Engine installation guide plus a few more (they do not conflict)

```
sudo apt-get install htop openjdk-8-jdk postgis postgresql-9.4-postgis-scripts postgresql postgresql-client tomcat8 tomcat8-admin ant pgadmin3 nodejs npm mongodb phppgadmin -y
```

# TOMCAT: adds the manager user, makes sure group and user are correctly set

```
sudo cp /vagrant/scripts/tomcat-users.xml /var/lib/tomcat8/conf/ 
sudo chown root /var/lib/tomcat8/conf/tomcat-users.xml 
sudo chgrp tomcat8 /var/lib/tomcat8/conf/tomcat-users.xml
sudo apt-get upgrade -y
```

# i use phppgadmin instead of pgadmin3

```
sudo cp /vagrant/scripts/phppgadmin /etc/apache2/conf-available/phppgadmin.conf 
```

   #omitted other commands to properly set up phppgadmin
    sudo service tomcat8 restart

At this point I create the vagrant user as postgresql superuser with password "vagrant". I can log in to postgresql with psql -U vagrant and its password.
After running the frontend with vagrant/vagrant, the postgresql server contains 2 extra databases (see image)

Q: Did you install PostgreSQL with POSTGIS support? Have you checked it?

A: all seems ok:
![postgis2](https://cloud.githubusercontent.com/assets/4893151/9854178/b744872e-5b07-11e5-9265-1ec5b7ccde02.png)

to be sure, I selected template1 database and launched CREATE EXTENSION postgis on it, and got a positive result:
![createextension](https://cloud.githubusercontent.com/assets/4893151/9853965/ac26f706-5b06-11e5-964f-7778503fbed1.png)

Q: There are some SQL files that are stored in POSTGIS? Have you tried that there are no problem via pgAdmin3 or a similar software?

A: I am not sure what you mean, this is what I see database-wise when checking through a web admin after having run once the frontend (note left column, 2 databases related to Fusion Engine have been created, table spatial_ref_sys is populated in both DBs, but valencia DB has only one table):
![pgadmin](https://cloud.githubusercontent.com/assets/4893151/9854577/b5d68886-5b09-11e5-9497-de245ae6ec84.png)

this is what I see on psql console:
![dbs](https://cloud.githubusercontent.com/assets/4893151/9854100/539835ae-5b07-11e5-8db7-1d17ff3dcea7.png)

Q: What version of Apache Tomcat and Linux are you using? Depending on the version, you should change the Tomcat installation directory in the SQL files. This is explained in the documentation files. This can be a potential reason.

A: Ubuntu Linux 14.10 server, Apache 8, postgresql 9.4

Q: Even if there is no message in the UI (snapshot), there are other ways to find the error. You should have a look at the Tomcat log file (/ logs/catalina.out) and the log file of the application (located in the same directory). Probably you should find here an ERROR informing about the error.

No error save one that said that the databases were already created. So I deleted them, relaunched the frontend, and the browser hung. (it's still "loading" on this page after 20 minutes). Databases were again created with the same tables as above.

I think it might be a matter of where I put and what to do with the fic_fe_v3.jar file, I am unclear on where to put it and how to "activate" it ....

many thanks

**Comment by benmomo** [comment]
Hi,
I will try to follow your steps in order to replicate the error. 
In the meantime, there are other ways in the way you can test the Fusion Engine:
- use theFiContent2 Lab (http://lab.mediafi.org/run.html). Here you can run any of the enablers deployed under the FiContent2 project
- use Docker. It seems to me that Docker is pretty much similar to vagrant. There is a dockerfile for the Fusion Engine that you can download and test immediately. You can find more info under the ficontent2 folder (https://github.com/satrd/poi_fusion_engine3/tree/master/ficontent2/docker)

Kind regards,
Benjamin

**Comment by mbariola** [comment]
Hi, the FIContent2 Lab has not been working properly lately, but I'll try the Docker box right now. Thanks!

EDIT: I just checked, Docker does not seem to run on Windows 10 yet. I'll need to find a machine with an older OS.

**Comment by benmomo** [comment]
By the way, the destination folder for the  'fic_fe_v3 jar' file (from your previous e-mail) does not matter, as long as it has the config.xml file and SQL script in the same folder and properly configured. It basically looks up in the database (ocd_base) periodically to 'scan' for new OCDs to be built. 
Such OCDs are initially created via the frontend service. You should be able to see two demo cities (Tenerife and Valencia) if the installation of the front end service is OK, without requiring the JAR file even to be launched. Otherwise, there is some problem during the installation. I will investigate further on it.

**Comment by mbariola** [comment]
yes, the two DBs are there, the ocd_base has many tables of which one is populated with almost 4K records, and the valencia one has only the spatial_rel_sys table with about 4K reords and nothing else.

Re. jar, So I can put it wherever I want and not call it at all? as in 

sudo cp .......release/service/\*  /var/FIWAREFF 

and that's it? no need to launch it with a java -jar or do anything? (sorry, but Java is really not my technology, I come from LAMP)

**Comment by benmomo** [comment]
Hi, the problem lies in the fact that the valencia and tenerife demo tables in POSTGIS are not being filled. There should be some error with the SQL initialization script. Otherwise you should have seen more than two tables (the one that enable POSTGIS).
The jar is just another Java process, thus you can put in whatever folder in Linux (where you have permissions, obvioulsy). While executing java -jar <file.jar> a new process is launched, it looks into the config XML file in order to coneect to the POSTGIS database and starts the process of fusion, if there a new OCD to be buillt. This is explained in the documentation files.

**Comment by mbariola** [comment]
Hi, 

ok, I finally got it. So basically I can either launch the jar manually whenever I need a different OCD or have it run as a service (it watches the DB), I must have missed this in the documentation ... I did read re. the ocd status.

while the frontend allows me to specify new OCDs, now the point is to understand why it freezes on creating the tables after the spatial_rel_sys. Anything I can look for?

**Comment by mbariola** [comment]
Ah, maybe I got it. Not 100% sure.

There are many lines where there is an explicit owner assignment:
ALTER TABLE seq_category_id OWNER TO postgres;

since I am running it with another superuser (vagrant) due to postgres user being locked down it _might_ be the issue. will try deleting the DBs and trying to force the user credentials

EDIT: tried it, no luck. the frontend stops at the same place ..

**Comment by benmomo** [comment]
Hi again, 
I've been trying to set up the Fusion Engine with Vagrant I just used
vagrant init boxcutter/ubuntu1410; vagrant up --provider virtualbox
changing the port forwarding after configuring tomcat
config.vm.network "forwarded_port", guest: 8080, host: 8085
in order to interact from my host computer

I installed all required packages, as in the documentation, added the manager-gui user in tomcat-users.xml and also allowed local access in pga_hba.conf (also highlghted in the doc):

# IPv4 local connections:

host    all             all             127.0.0.1/32            trust
After restarting tomcat and Postgres, I downloaded the ZIP project from github, in order to use the WAR file under the release/frontend folder
I have opened the browser from my host computer (localhost:8085) and access the manager GUI of the vagrant box. After deployment, in the initial step, I was able to initialize all databases successfully. Finally I was able to see the POIs from the two demo cities:
![snapshot](https://cloud.githubusercontent.com/assets/9946208/9880436/e89f56c2-5bcb-11e5-9cc7-3ecc6749dacc.png)
It seems that it works fine without any special configuration requirement. So it seem it is something with the configuration in your vagrant box:
a) If you can, please check with this one  (boxcutter/ubuntu1410). I have just selected the same Ubuntu version as you
b) Please check that Tomcat and POSTGIS where correctly configured. In the box I'm using, the postgres user is the root user in POSTGIS and used for generating and building new databases. If you are using another user (vagrant), please verify that you have also admin privileges in POSTGIS and that you are allowed to connect locally

**Comment by mbariola** [comment]
Hi Benjamin, thanks for the detailed advancement. Yes, I use the boxcutter box too.
There is one thing that might be the issue - you mention a POSTGIS user configuration? I only did a postgresql user configuration (tried with both postgres and vagrant users, both superadmins). Is there anything I need to do re. POSTGIS?

this is from my current pg_hba.conf: (not pga_hba.conf)

local   all             postgres                      trust
local     all          vagrant                trust

(tried all possible combinations of peer, trust, md5 etc. - also made sure that vagrant has superuser rights in postgresql. I can start the generation of databases from frontend with both users, but it hangs.)

those are the only two users in pg_hba.conf, nothing specific for POSTGIS. I thought it was a simple extension to postgresql, is there any configuration I need to do?

would you attach your pg_hba.conf to be sure? 
Or you could push your box in the repository at this point and I can dig into it myself and see what differences are there...
Thanks

**Comment by benmomo** [comment]
Hi,
no the POSTGIS user configuration is the postgresql one. I just changed the line in pg_hba.conf to:
host all all 127.0.0.1/32 trust
I will try to push the box anyway, but it does not seem very easy at first glance..

**Comment by mbariola** [comment]
I destroyed my virtual machine to be sure and started anew. At first I kept getting a lot of errors re. the frontend not being able to access the db, even if I changed the postgresql password.

Then I read better your last comment re. host all all 127.0.0.1/32 trust

you wrote _change_ , not _add_ , still I was adding the line at the end (after the replication ones)
then after inputting for the Nth time the modifications to reload, I noticed that there was a 

host all all 127.0.0.1/32 md5

between lines of comment. AHA!

deleted my own line, _changed_ as you wrote that line, and .....

![yay](https://cloud.githubusercontent.com/assets/4893151/9891863/eae2c976-5c09-11e5-9f67-891bba8c74eb.png)

Finally :-)

Thanks for helping with fixing that, one thing I'd improve in the accompanying docs is

change
"If required, remember to grant user access at /etc/postgresql/9.X/main/pg_hba.conf"
into
"If required, remember to grant user access at /etc/postgresql/9.X/main/pg_hba.conf changing the line
host    all             all             127.0.0.1/32            md5
to
host    all             all             127.0.0.1/32            trust
Please note that this might be a security hazard as all applications running on the server will be able to access the database with any user, so take appropriate mitigation steps based on how much you trust the other apps running on the server"

That should help other devs who aren't much skilled with postgresql.

Thanks again! from tomorrow it's test drive time.
